version: 1.0.9.{build}
image: Visual Studio 2017
build:
  publish_nuget: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: 7UVhBBlyrW1vb6+6AgYmQjGP4y+upNse1BJcgDYlIoF87oNVHgEq3tj4CL/g5cFN