version: 1.0.8.{build}
build:
  verbosity: minimal
deploy:
  provider: NuGet
  server:                 
  api_key:
    secure: 7UVhBBlyrW1vb6+6AgYmQjGP4y+upNse1BJcgDYlIoF87oNVHgEq3tj4CL/g5cFN
  skip_symbols: false
  symbol_server:          
  artifact: /.*\.nupkg/